#!/usr/bin/env bash
# Commit each modified file individually
FILES=(
  "docs/hermes/services/gardien-drive.md"
  "docs/hermes/services/gestion-releases.md"
  "docs/hermes/services/n8n.md"
  "docs/hermes/services/pre-migration-v017.md"
  "docs/hermes/services/spotify.md"
  "docs/hermes/skills/ch16-skills-systeme.md"
  "docs/hermes/skills/ch19-skills-creatifs.md"
  "docs/hermes/skills/ch20-skills-recherche.md"
  "docs/hermes/skills/ch21-ecrire-ses-skills.md"
  "docs/hermes/TABLE.md"
  "docs/hermes/utilisation/architecture-leo.md"
  "docs/hermes/utilisation/backup-recovery.md"
  "docs/hermes/utilisation/bots-telegram.md"
  "docs/hermes/utilisation/crons.md"
  "docs/hermes/utilisation/dashboards.md"
  "docs/hermes/utilisation/documentation-map.md"
  "docs/hermes/utilisation/quotidien.md"
  "docs/hermes/utilisation/skills-catalogue.md"
  "docs/hermes/configuration/profiles.md"
  "docs/hermes/configuration/providers.md"
  "docs/hermes/configurer/ch05-gateway-profils.md"
  "docs/hermes/configurer/ch06-providers.md"
  "docs/hermes/configurer/ch07-multi-bots.md"
  "docs/hermes/configurer/ch08-skills.md"
  "docs/hermes/configurer/ch09-memoire.md"
  "docs/hermes/dashboards/ch22-dashboards-intro.md"
  "docs/hermes/dashboards/ch23-metriques-machines.md"
  "docs/hermes/dashboards/ch25-budget-tracking.md"
  "docs/hermes/dashboards/n8n.md"
  "docs/hermes/decisions/pourquoi-deepseek-pas-gemini.md"
  "docs/hermes/automatisation/ch26-crons-intro.md"
  "docs/hermes/automatisation/ch28-crons-quotidiens.md"
  "docs/hermes/automatisation/ch29-watchdogs.md"
  "docs/hermes/automatisation/ch30-drive-github-sync.md"
  "docs/hermes/bureaux/ch10-architecture-bureaux.md"
  "docs/hermes/bureaux/ch11-bureau-michel.md"
  "docs/hermes/bureaux/ch12-bureau-sylvia.md"
  "docs/hermes/bureaux/ch13-bureau-emile.md"
  "docs/hermes/bureaux/ch14-bureau-robert.md"
  "docs/hermes/bureaux/ch15-bureau-leo.md"
  "docs/hermes/interface-web.md"
)

for f in "${FILES[@]}"; do
  git add "$f" && git commit -m "docs: harmonisation date footer"
done
